import OBR from "https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0";
import {ROOM_KEY,SYNC_CHANNEL,SHEET_MODAL_ID,defaultCatalog,normalizeCatalog,loadStore,saveStore,normalizeCharacter,catalogSummary,classLabel,escapeHtml,cacheKey,saveCache} from "./core.js";
const $=s=>document.querySelector(s); const state={role:"PLAYER",playerId:"preview",connectionId:"preview",name:"Agente",roomId:"preview-room",catalog:defaultCatalog(),party:[],store:{}};
function pct(v,m){return m>0?Math.max(0,Math.min(100,(v/m)*100)):0}
function roleName(){return state.role==="GM"?"Mestre":"Jogador"}
async function setCatalog(next){ state.catalog=normalizeCatalog(next,state.playerId); if(OBR.isAvailable&&state.role==="GM")await OBR.room.setMetadata({[ROOM_KEY]:state.catalog}); render(); }
function visibleChars(){return state.role==="GM"?state.catalog.characters:state.catalog.characters.filter(c=>c.controllers?.includes(state.playerId))}
function controllerOptions(c){ const all=[{id:"",name:"Sem controlador"},...state.party.filter(p=>p.role==="PLAYER").map(p=>({id:p.id,name:p.name||"Jogador"}))]; const current=c.controllers?.[0]||""; return all.map(p=>`<option value="${escapeHtml(p.id)}" ${p.id===current?"selected":""}>${escapeHtml(p.name)}</option>`).join(""); }
function resource(key,c){const r=c[key],p=pct(Number(r?.value)||0,Number(r?.max)||0);return `<div class="resource ${key.toLowerCase()}"><span><b>${key}</b><em>${r?.value??0}/${r?.max??0}</em></span><div class="bar"><i style="width:${p}%"></i></div></div>`}
function card(c){const meta=[classLabel(c.class),c.trilha||c.origin,`NEX ${c.NEX??0}%`].filter(Boolean).join(" // "); return `<article class="agent-card" data-id="${escapeHtml(c.id)}"><div class="agent-main" data-open="${escapeHtml(c.id)}"><div class="portrait">${c.portrait?`<img src="${escapeHtml(c.portrait)}" alt="">`:"◇"}</div><div class="agent-info"><h3>${escapeHtml(c.name)}</h3><div class="agent-meta">${escapeHtml(meta)}</div><div class="resource-row">${resource("PV",c)}${resource("PE",c)}${resource("SAN",c)}</div></div></div>${state.role==="GM"?`<div class="controller-row"><label>CONTROLADOR</label><select class="controller-select" data-controller="${escapeHtml(c.id)}">${controllerOptions(c)}</select><button class="open-chip" data-open="${escapeHtml(c.id)}">ABRIR</button></div>`:""}</article>`}
function render(){ $("#identity").textContent=`${state.name} · ${roleName()}`; const chars=visibleChars(); $("#heading").textContent=state.role==="GM"?"PERSONAGENS":"MEUS AGENTES"; $("#subheading").textContent=state.role==="GM"?"Crie, atribua e acompanhe as fichas da mesa.":"Fichas sob sua responsabilidade nesta sala."; $("#newAgent").classList.toggle("hidden",state.role!=="GM"); $("#stats").innerHTML=state.role==="GM"?`<div class="stat"><span>AGENTES</span><strong>${state.catalog.characters.length}</strong></div><div class="stat"><span>ATRIBUÍDOS</span><strong>${state.catalog.characters.filter(c=>c.controllers?.length).length}</strong></div><div class="stat"><span>ONLINE</span><strong>${state.party.length+1}</strong></div>`:`<div class="stat"><span>FICHAS</span><strong>${chars.length}</strong></div><div class="stat"><span>SALA</span><strong>SYNC</strong></div><div class="stat"><span>ACESSO</span><strong>DSO</strong></div>`; $("#agentList").innerHTML=chars.map(card).join(""); $("#empty").classList.toggle("hidden",chars.length>0); $("#emptyText").textContent=state.role==="GM"?"Crie o primeiro agente da sala.":"O Mestre ainda não atribuiu uma ficha a você."; }
async function openSheet(id,newSheet=false){if(!OBR.isAvailable){alert("Abra a extensão dentro do Owlbear Rodeo.");return;} await OBR.modal.open({id:SHEET_MODAL_ID,url:newSheet?"/sheet.html?new=1":`/sheet.html?id=${encodeURIComponent(id)}`,fullScreen:true});}
async function assignController(id,playerId){ if(state.role!=="GM")return; const ch=state.store[id]; if(!ch)return; ch.controllers=playerId?[playerId]:[]; ch.updatedAt=Date.now(); state.store[id]=normalizeCharacter(ch); saveStore(state.roomId,state.store); state.catalog.characters=state.catalog.characters.map(x=>x.id===id?catalogSummary(state.store[id]):x); await setCatalog(state.catalog); await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"catalog-changed"},{destination:"REMOTE"}); }
function download(name,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
async function init(){ if(!OBR.isAvailable){ $("#loading").classList.add("hidden"); state.role="GM"; state.name="Prévia"; state.catalog=defaultCatalog("preview"); render(); return;} await new Promise(r=>OBR.onReady(r)); [state.role,state.name,state.connectionId]=await Promise.all([OBR.player.getRole(),OBR.player.getName(),OBR.player.getConnectionId()]); state.playerId=OBR.player.id;state.roomId=OBR.room.id;state.party=await OBR.party.getPlayers(); const meta=await OBR.room.getMetadata(); state.catalog=normalizeCatalog(meta[ROOM_KEY],state.role==="GM"?state.playerId:""); if(state.role==="GM"){ state.store=loadStore(state.roomId); if(!meta[ROOM_KEY])await setCatalog(state.catalog); // reconcile existing local data
   const summaries=Object.values(state.store).map(x=>catalogSummary(normalizeCharacter(x))); if(summaries.length&&!state.catalog.characters.length){state.catalog.characters=summaries;await setCatalog(state.catalog);} }
 render(); $("#loading").classList.add("hidden"); OBR.party.onChange(p=>{state.party=p;render()}); OBR.room.onMetadataChange(m=>{state.catalog=normalizeCatalog(m[ROOM_KEY],state.catalog.gmId);render()}); OBR.broadcast.onMessage(SYNC_CHANNEL,e=>{if(e.data?.type==="catalog-changed")void OBR.room.getMetadata().then(m=>{state.catalog=normalizeCatalog(m[ROOM_KEY],state.catalog.gmId);render()})}); }
$("#newAgent").addEventListener("click",()=>openSheet("",true)); $("#menuBtn").addEventListener("click",()=>$("#menu").classList.toggle("hidden")); $("#refreshBtn").addEventListener("click",()=>location.reload());
$("#agentList").addEventListener("click",e=>{const el=e.target.closest("[data-open]");if(el)void openSheet(el.dataset.open)}); $("#agentList").addEventListener("change",e=>{const el=e.target.closest("[data-controller]");if(el)void assignController(el.dataset.controller,el.value)});
$("#exportBtn").addEventListener("click",()=>{if(state.role!=="GM")return alert("Apenas o Mestre exporta o banco da sala."); download(`dso-system-${state.roomId}.json`,{version:1,catalog:state.catalog,characters:state.store})});
$("#importInput").addEventListener("change",async e=>{if(state.role!=="GM")return;const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());const incoming=data.characters||{};for(const [id,c] of Object.entries(incoming))state.store[id]=normalizeCharacter(c);saveStore(state.roomId,state.store);state.catalog.characters=Object.values(state.store).map(c=>catalogSummary(c));await setCatalog(state.catalog);alert("Backup importado.");}catch(err){alert("Arquivo de backup inválido.")}}); init();