import OBR from "https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0";
import {ROOM_KEY,LEGACY_ROOM_KEY,SYNC_CHANNEL,SKILL_BRIDGE_CHANNEL,SHEET_MODAL_ID,defaultCatalog,normalizeCatalog,loadStore,saveStore,normalizeCharacter,catalogSummary,classLabel,escapeHtml,profileFromCharacter} from "./core.js";
const $=s=>document.querySelector(s);const state={role:"PLAYER",playerId:"preview",name:"Protagonista",roomId:"preview-room",catalog:defaultCatalog(),party:[],store:{}};
function pct(v,m){return m>0?Math.max(0,Math.min(100,(Number(v)||0)/(Number(m)||1)*100)):0}function roleName(){return state.role==="GM"?"Mestre":"Jogador"}
async function setCatalog(next){state.catalog=normalizeCatalog(next,state.playerId);if(OBR.isAvailable&&state.role==="GM")await OBR.room.setMetadata({[ROOM_KEY]:state.catalog});render();}
function visibleChars(){return state.role==="GM"?state.catalog.characters:state.catalog.characters.filter(c=>c.controllers?.includes(state.playerId))}
function controllerOptions(c){const all=[{id:"",name:"Sem controlador"},...state.party.filter(p=>p.role==="PLAYER").map(p=>({id:p.id,name:p.name||"Jogador"}))],current=c.controllers?.[0]||"";return all.map(p=>`<option value="${escapeHtml(p.id)}" ${p.id===current?"selected":""}>${escapeHtml(p.name)}</option>`).join("")}
function resource(key,c){const r=c[key]||{value:0,max:0},p=pct(r.value,r.max);return `<div class="resource ${key.toLowerCase()}"><span><b>${key}</b><em>${r.value??0}/${r.max??0}</em></span><div class="bar"><i style="width:${p}%"></i></div></div>`}
function card(c){
  const meta=[classLabel(c.class),`NÍVEL ${c.nivel??1}`,`NEX ${c.NEX??0}%`,c.trilha||c.origin].filter(Boolean).join(" // ");
  return `<article class="agent-card">
    <div class="agent-main" data-open="${escapeHtml(c.id)}">
      <div class="doc-mark" aria-hidden="true"><img src="/icon.svg" alt=""></div>
      <div class="agent-info"><h3>${escapeHtml(c.name)}</h3><div class="agent-meta">${escapeHtml(meta)}</div><div class="resource-row">${resource("PV",c)}${resource("PD",c)}</div></div>
    </div>
    ${state.role==="GM"?`<div class="controller-row"><label>CONTROLADOR</label><select class="controller-select" data-controller="${escapeHtml(c.id)}">${controllerOptions(c)}</select><button class="open-chip" data-open="${escapeHtml(c.id)}">ABRIR</button><button class="delete-chip" data-delete="${escapeHtml(c.id)}" title="Excluir protagonista" aria-label="Excluir protagonista"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m-8 0 1 13h8l1-13M10 11v6m4-6v6"/></svg></button></div>`:""}
  </article>`
}
function render(){const chars=visibleChars();$("#identity").textContent=`${state.name} · ${roleName()}`;$("#heading").textContent=state.role==="GM"?"PROTAGONISTAS":"MEUS PROTAGONISTAS";$("#subheading").textContent=state.role==="GM"?"Crie, atribua e acompanhe as fichas da mesa.":"Fichas sob sua responsabilidade nesta sala.";$("#newAgent").classList.toggle("hidden",state.role!=="GM");$("#stats").innerHTML=state.role==="GM"?`<div class="stat"><span>PROTAGONISTAS</span><strong>${state.catalog.characters.length}</strong></div><div class="stat"><span>ATRIBUÍDOS</span><strong>${state.catalog.characters.filter(c=>c.controllers?.length).length}</strong></div><div class="stat"><span>ONLINE</span><strong>${state.party.length+1}</strong></div>`:`<div class="stat"><span>FICHAS</span><strong>${chars.length}</strong></div><div class="stat"><span>REGRAS</span><strong>PD</strong></div><div class="stat"><span>NÍVEL / NEX</span><strong>SEPARADOS</strong></div>`;$("#agentList").innerHTML=chars.map(card).join("");$("#empty").classList.toggle("hidden",chars.length>0);$("#emptyText").textContent=state.role==="GM"?"Crie o primeiro protagonista da sala.":"O Mestre ainda não atribuiu uma ficha a você.";}
async function openSheet(id,newSheet=false){if(!OBR.isAvailable)return alert("Abra a extensão dentro do Owlbear Rodeo.");await OBR.modal.open({id:SHEET_MODAL_ID,url:newSheet?"/sheet.html?new=1":`/sheet.html?id=${encodeURIComponent(id)}`,fullScreen:true});}
async function assignController(id,pid){if(state.role!=="GM")return;const ch=state.store[id];if(!ch)return;ch.controllers=pid?[pid]:[];ch.updatedAt=Date.now();state.store[id]=normalizeCharacter(ch);saveStore(state.roomId,state.store);state.catalog.characters=state.catalog.characters.map(x=>x.id===id?catalogSummary(state.store[id]):x);await setCatalog(state.catalog);await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"catalog-changed"},{destination:"REMOTE"});if(pid){const player=state.party.find(p=>p.id===pid);if(player?.connectionId)await OBR.broadcast.sendMessage(SKILL_BRIDGE_CHANNEL,{type:"profile",targetConnectionId:player.connectionId,profile:profileFromCharacter(state.store[id])},{destination:"REMOTE"});}}
async function deleteCharacter(id){
  if(state.role!=="GM")return;
  const ch=state.store[id]; if(!ch)return;
  if(!confirm(`Excluir ${ch.name || "este protagonista"}? Esta ação remove a ficha desta sala.`))return;
  delete state.store[id];
  saveStore(state.roomId,state.store);
  state.catalog.characters=state.catalog.characters.filter(x=>x.id!==id);
  await setCatalog(state.catalog);
  await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-deleted",characterId:id},{destination:"ALL"});
  toastDeleted(ch.name||"Protagonista");
}
function toastDeleted(name){try{OBR.notification.show(`${name} excluído do DSO System.`)}catch{}}

function download(name,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
async function init(){if(!OBR.isAvailable){$("#loading").classList.add("hidden");state.role="GM";state.name="Prévia";render();return;}await new Promise(r=>OBR.onReady(r));[state.role,state.name]=await Promise.all([OBR.player.getRole(),OBR.player.getName()]);state.playerId=OBR.player.id;state.roomId=OBR.room.id;state.party=await OBR.party.getPlayers();const meta=await OBR.room.getMetadata();state.catalog=normalizeCatalog(meta[ROOM_KEY]||meta[LEGACY_ROOM_KEY],state.role==="GM"?state.playerId:"");if(state.role==="GM"){state.store=loadStore(state.roomId);for(const [id,c] of Object.entries(state.store))state.store[id]=normalizeCharacter(c);saveStore(state.roomId,state.store);const summaries=Object.values(state.store).map(c=>catalogSummary(c));if(summaries.length){state.catalog.characters=summaries;await setCatalog(state.catalog);}else if(!meta[ROOM_KEY])await setCatalog(state.catalog);}render();$("#loading").classList.add("hidden");OBR.party.onChange(p=>{state.party=p;render()});OBR.room.onMetadataChange(m=>{state.catalog=normalizeCatalog(m[ROOM_KEY]||m[LEGACY_ROOM_KEY],state.catalog.gmId);render()});OBR.broadcast.onMessage(SYNC_CHANNEL,e=>{if(e.data?.type==="catalog-changed")void OBR.room.getMetadata().then(m=>{state.catalog=normalizeCatalog(m[ROOM_KEY]||m[LEGACY_ROOM_KEY],state.catalog.gmId);render()})});}
$("#newAgent").addEventListener("click",()=>openSheet("",true));$("#menuBtn").addEventListener("click",()=>$("#menu").classList.toggle("hidden"));$("#refreshBtn").addEventListener("click",()=>location.reload());$("#agentList").addEventListener("click",e=>{const del=e.target.closest("[data-delete]");if(del){void deleteCharacter(del.dataset.delete);return;}const el=e.target.closest("[data-open]");if(el)void openSheet(el.dataset.open)});$("#agentList").addEventListener("change",e=>{const el=e.target.closest("[data-controller]");if(el)void assignController(el.dataset.controller,el.value)});$("#exportBtn").addEventListener("click",()=>{if(state.role!=="GM")return alert("Apenas o Mestre exporta o banco da sala.");download(`dso-system-${state.roomId}.json`,{version:2,catalog:state.catalog,characters:state.store})});$("#importInput").addEventListener("change",async e=>{if(state.role!=="GM")return;const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text()),incoming=data.characters||{};for(const [id,c] of Object.entries(incoming))state.store[id]=normalizeCharacter(c);saveStore(state.roomId,state.store);state.catalog.characters=Object.values(state.store).map(c=>catalogSummary(c));await setCatalog(state.catalog);alert("Backup importado.");}catch{alert("Arquivo de backup inválido.")}});init();
