import OBR,{buildShape} from "https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0";
import {ID,ROOM_KEY,LEGACY_ROOM_KEY,SYNC_CHANNEL,SKILL_BRIDGE_CHANNEL,TOKEN_KEY,LEGACY_TOKEN_KEY,BAR_KEY,SHEET_MODAL_ID,LINK_MODAL_ID,RESOURCE_MODAL_ID,normalizeCatalog,loadStore,saveStore,normalizeCharacter,catalogSummary,isAuthorized,profileFromCharacter} from "./core.js";
let role="PLAYER",playerId="",roomId="",connectionId="";
async function senderPlayer(event){const party=await OBR.party.getPlayers();return party.find(p=>p.connectionId===event.connectionId)||null}
async function updateCatalogFor(c){const m=await OBR.room.getMetadata(),cat=normalizeCatalog(m[ROOM_KEY]||m[LEGACY_ROOM_KEY],playerId),idx=cat.characters.findIndex(x=>x.id===c.id),summary=catalogSummary(c);if(idx>=0)cat.characters[idx]=summary;else cat.characters.push(summary);await OBR.room.setMetadata({[ROOM_KEY]:cat})}
function tokenLink(item){return item?.metadata?.[TOKEN_KEY]||item?.metadata?.[LEGACY_TOKEN_KEY]||null}
async function sendProfile(c,targetConnectionId){if(!c||!targetConnectionId)return;await OBR.broadcast.sendMessage(SKILL_BRIDGE_CHANNEL,{type:"profile",targetConnectionId,profile:profileFromCharacter(c)},{destination:"REMOTE"})}
async function sendProfilesFor(c){const party=await OBR.party.getPlayers();for(const pid of c.controllers||[]){const p=party.find(x=>x.id===pid);if(p?.connectionId)await sendProfile(c,p.connectionId)}}
async function removeBars(tokenId){const all=await OBR.scene.items.getItemAttachments([tokenId]);const ids=all.filter(i=>i.id!==tokenId&&i.metadata?.[BAR_KEY]?.tokenId===tokenId).map(i=>i.id);if(ids.length)await OBR.scene.items.deleteItems(ids)}
async function refreshTokenBars(token,c){if(role!=="GM"||!token||!c)return;await removeBars(token.id);let bounds;try{bounds=await OBR.scene.items.getItemBounds([token.id])}catch{return}const width=Math.max(60,Number(bounds.width||80)*.9),h=Math.max(5,Math.min(10,width*.035)),x=Number(bounds.min?.x??token.position?.x??0)+(Number(bounds.width||width)-width)/2,y=Number(bounds.max?.y??token.position?.y??0)+7;const ratio=(r)=>r.max>0?Math.max(0,Math.min(1,r.value/r.max)):0;const meta=(kind)=>({[BAR_KEY]:{tokenId:token.id,characterId:c.id,kind}});const common=(b,kind,px,py,w,color)=>b.width(w).height(h).shapeType("RECTANGLE").position({x:px,y:py}).fillColor(color).fillOpacity(1).strokeColor("#050608").strokeOpacity(1).strokeWidth(1).layer("ATTACHMENT").attachedTo(token.id).locked(true).disableHit(true).disableAutoZIndex(true).metadata(meta(kind)).name(`DSO ${kind}`).build();const pvBg=common(buildShape(),"pv-bg",x,y,width,"#24282f"),pvFill=common(buildShape(),"pv-fill",x,y,width*ratio(c.system.PV),"#bd303b"),pdY=y+h+3,pdBg=common(buildShape(),"pd-bg",x,pdY,width,"#24282f"),pdFill=common(buildShape(),"pd-fill",x,pdY,width*ratio(c.system.PD),"#d9dde2");await OBR.scene.items.addItems([pvBg,pvFill,pdBg,pdFill])}
async function refreshBarsForCharacter(characterId){if(role!=="GM")return;const store=loadStore(roomId),c=store[characterId];if(!c)return;const items=await OBR.scene.items.getItems(i=>i.layer==="CHARACTER"&&tokenLink(i)?.id===characterId);for(const token of items)await refreshTokenBars(token,c)}
async function setup(){if(!OBR.isAvailable)return;await new Promise(r=>OBR.onReady(r));[role,connectionId]=await Promise.all([OBR.player.getRole(),OBR.player.getConnectionId()]);playerId=OBR.player.id;roomId=OBR.room.id;
  OBR.broadcast.onMessage(SYNC_CHANNEL,async event=>{const d=event.data||{};if(role!=="GM")return;if(d.type==="token-linked"&&d.characterId){await refreshBarsForCharacter(d.characterId);return}const sender=await senderPlayer(event);if(!sender)return;const store=loadStore(roomId),current=store[d.characterId];if(d.type==="request-character"&&current&&isAuthorized(current,sender.id,sender.role))await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-snapshot",requestId:d.requestId,targetConnectionId:event.connectionId,character:current},{destination:"REMOTE"});if(d.type==="update-character"&&current&&isAuthorized(current,sender.id,sender.role)){const incoming=normalizeCharacter(d.character);incoming.id=current.id;incoming.controllers=[...(current.controllers||[])];incoming.createdAt=current.createdAt;incoming.updatedAt=Date.now();store[incoming.id]=incoming;saveStore(roomId,store);await updateCatalogFor(incoming);await refreshBarsForCharacter(incoming.id);await sendProfilesFor(incoming);await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"update-result",requestId:d.requestId,targetConnectionId:event.connectionId,ok:true,character:incoming},{destination:"REMOTE"});await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-updated",characterId:incoming.id,character:incoming},{destination:"REMOTE"})}if(d.type==="resource-update"&&current&&isAuthorized(current,sender.id,sender.role)){current.system.PV.value=Math.max(0,Math.min(current.system.PV.max,Number(d.PV??current.system.PV.value)));current.system.PD.value=Math.max(0,Math.min(current.system.PD.max,Number(d.PD??current.system.PD.value)));current.updatedAt=Date.now();store[current.id]=normalizeCharacter(current);saveStore(roomId,store);await updateCatalogFor(store[current.id]);await refreshBarsForCharacter(current.id);await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-updated",characterId:current.id,character:store[current.id]},{destination:"REMOTE"})}});
  OBR.broadcast.onMessage(SKILL_BRIDGE_CHANNEL,async event=>{const d=event.data||{};if(role!=="GM"||d.type!=="request-profile")return;const sender=await senderPlayer(event);if(!sender)return;const store=loadStore(roomId),c=Object.values(store).map(normalizeCharacter).find(x=>x.controllers?.includes(sender.id));if(c)await sendProfile(c,event.connectionId)});
  await OBR.contextMenu.create({id:`${ID}/token-sheet`,icons:[{icon:"/icon.svg",label:"DSO System — Protagonista",filter:{every:[{key:"layer",value:"CHARACTER"}]}}],async onClick(ctx){const item=ctx.items?.[0];if(!item)return;const link=tokenLink(item);if(link?.id){await OBR.modal.open({id:SHEET_MODAL_ID,url:`/sheet.html?id=${encodeURIComponent(link.id)}`,fullScreen:true});return}if(role!=="GM"){OBR.notification.show("Este token ainda não possui protagonista DSO vinculado.");return}localStorage.setItem(`dso.system.pending-link.${roomId}`,JSON.stringify(ctx.items.map(i=>i.id)));await OBR.modal.open({id:LINK_MODAL_ID,url:"/link.html",width:440,height:560})}});
  await OBR.contextMenu.create({id:`${ID}/token-resources`,icons:[{icon:"/resources.svg",label:"DSO System — PV / PD",filter:{every:[{key:"layer",value:"CHARACTER"},{key:["metadata",TOKEN_KEY],value:undefined,operator:"!="}]}}],async onClick(ctx){const item=ctx.items?.[0],link=tokenLink(item);if(!link?.id)return;await OBR.modal.open({id:RESOURCE_MODAL_ID,url:`/resources.html?id=${encodeURIComponent(link.id)}`,width:390,height:310})}}).catch(()=>{});
  if(role==="GM"){const store=loadStore(roomId),tokens=await OBR.scene.items.getItems(i=>i.layer==="CHARACTER"&&tokenLink(i)?.id);for(const token of tokens){const c=store[tokenLink(token).id];if(c)await refreshTokenBars(token,normalizeCharacter(c))}for(const c of Object.values(store)){await sendProfilesFor(normalizeCharacter(c))}}
}
setup().catch(console.error);
