import OBR from "https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0"; import {ID,ROOM_KEY,SYNC_CHANNEL,TOKEN_KEY,SHEET_MODAL_ID,LINK_MODAL_ID,normalizeCatalog,loadStore,saveStore,normalizeCharacter,catalogSummary,isAuthorized} from "./core.js";
let role="PLAYER",playerId="",roomId="",connectionId="";
async function senderPlayer(event){const party=await OBR.party.getPlayers();return party.find(p=>p.connectionId===event.connectionId)||null}
async function updateCatalogFor(c){const m=await OBR.room.getMetadata();const cat=normalizeCatalog(m[ROOM_KEY],playerId);const idx=cat.characters.findIndex(x=>x.id===c.id);const summary=catalogSummary(c);if(idx>=0)cat.characters[idx]=summary;else cat.characters.push(summary);await OBR.room.setMetadata({[ROOM_KEY]:cat});}
async function setup(){if(!OBR.isAvailable)return;await new Promise(r=>OBR.onReady(r));[role,connectionId]=await Promise.all([OBR.player.getRole(),OBR.player.getConnectionId()]);playerId=OBR.player.id;roomId=OBR.room.id;
 OBR.broadcast.onMessage(SYNC_CHANNEL,async event=>{const d=event.data||{};if(role!=="GM")return;const sender=await senderPlayer(event);if(!sender)return;const store=loadStore(roomId);const current=store[d.characterId];if(d.type==="request-character"&&current&&isAuthorized(current,sender.id,sender.role)){await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-snapshot",requestId:d.requestId,targetConnectionId:event.connectionId,character:current},{destination:"REMOTE"});}
 if(d.type==="update-character"&&current&&isAuthorized(current,sender.id,sender.role)){const incoming=normalizeCharacter(d.character);incoming.id=current.id;incoming.controllers=[...(current.controllers||[])];incoming.createdAt=current.createdAt;incoming.updatedAt=Date.now();store[incoming.id]=incoming;saveStore(roomId,store);await updateCatalogFor(incoming);await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"update-result",requestId:d.requestId,targetConnectionId:event.connectionId,ok:true,character:incoming},{destination:"REMOTE"});await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-updated",characterId:incoming.id,character:incoming},{destination:"REMOTE"});}});
 OBR.contextMenu.create({id:`${ID}/token-character`,icons:[{icon:"/icon.svg",label:"DSO System — ficha",filter:{every:[{key:"layer",value:"CHARACTER"}]}}],async onClick(ctx){const item=ctx.items?.[0];if(!item)return;const link=item.metadata?.[TOKEN_KEY];if(link?.id){await OBR.modal.open({id:SHEET_MODAL_ID,url:`/sheet.html?id=${encodeURIComponent(link.id)}`,fullScreen:true});return;}if(role!=="GM"){OBR.notification.show("Este token ainda não possui ficha DSO vinculada.");return;}localStorage.setItem(`dso.system.pending-link.${roomId}`,JSON.stringify(ctx.items.map(i=>i.id)));await OBR.modal.open({id:LINK_MODAL_ID,url:"/link.html",width:430,height:520});}});
}
setup();