import OBR from "https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0";
import {ROOM_KEY,LEGACY_ROOM_KEY,SYNC_CHANNEL,RESOURCE_MODAL_ID,loadStore,saveStore,normalizeCharacter,normalizeCatalog,catalogSummary,isAuthorized,clamp} from "./core.js";
const id=new URLSearchParams(location.search).get("id")||"";
let role="PLAYER",playerId="",connectionId="",roomId="",character=null,requestId="";
const $=s=>document.querySelector(s);
function render(){if(!character)return;const s=character.system;$("#name").textContent=character.name||"PROTAGONISTA";for(const [k,r] of [["pv",s.PV],["pd",s.PD]]){$(`#${k}-current`).textContent=Math.round(r.value);$(`#${k}-max`).textContent=Math.round(r.max);$(`#${k}-input`).value=Math.round(r.value);$(`#${k}-input`).max=Math.max(0,r.max);$(`#${k}-fill`).style.width=`${r.max?Math.max(0,Math.min(100,r.value/r.max*100)):0}%`;}$(`#loading`).classList.add("hidden")}
function setValue(kind,value){if(!character)return;const r=character.system[kind];r.value=clamp(value,0,r.max);render()}
async function readAsGM(){const store=loadStore(roomId),c=store[id];if(!c)throw new Error("Protagonista não encontrado.");character=normalizeCharacter(c);render()}
async function requestRemote(){requestId=crypto.randomUUID();await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"request-character",characterId:id,requestId},{destination:"REMOTE"})}
async function updateRoomCatalog(c){const m=await OBR.room.getMetadata(),cat=normalizeCatalog(m[ROOM_KEY]||m[LEGACY_ROOM_KEY],playerId),i=cat.characters.findIndex(x=>x.id===c.id),summary=catalogSummary(c);if(i>=0)cat.characters[i]=summary;else cat.characters.push(summary);await OBR.room.setMetadata({[ROOM_KEY]:cat})}
async function save(){if(!character)return;const PV=clamp($("#pv-input").value,0,character.system.PV.max),PD=clamp($("#pd-input").value,0,character.system.PD.max);$("#save").disabled=true;$("#status").textContent="ATUALIZANDO…";try{if(role==="GM"){character.system.PV.value=PV;character.system.PD.value=PD;character.updatedAt=Date.now();character=normalizeCharacter(character);const store=loadStore(roomId);store[character.id]=character;saveStore(roomId,store);await updateRoomCatalog(character);await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"token-linked",characterId:character.id},{destination:"ALL"});await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"character-updated",characterId:character.id,character},{destination:"REMOTE"});}else{await OBR.broadcast.sendMessage(SYNC_CHANNEL,{type:"resource-update",characterId:id,PV,PD},{destination:"REMOTE"});}$("#status").textContent="SALVO // SINCRONIZADO";setTimeout(()=>OBR.modal.close(RESOURCE_MODAL_ID),180);}catch(e){console.error(e);$("#status").textContent="ERRO AO SALVAR";$("#save").disabled=false}}
async function init(){await new Promise(r=>OBR.onReady(r));[role,connectionId]=await Promise.all([OBR.player.getRole(),OBR.player.getConnectionId()]);playerId=OBR.player.id;roomId=OBR.room.id;OBR.broadcast.onMessage(SYNC_CHANNEL,event=>{const d=event.data||{};if(d.type==="character-snapshot"&&d.requestId===requestId&&d.targetConnectionId===connectionId){character=normalizeCharacter(d.character);render()}if(d.type==="character-updated"&&d.characterId===id&&d.character){character=normalizeCharacter(d.character);render()}});if(role==="GM")await readAsGM();else await requestRemote()}
document.addEventListener("click",e=>{const b=e.target.closest("[data-step]");if(b){const [k,n]=b.dataset.step.split(":");setValue(k,Number(character?.system?.[k]?.value||0)+Number(n));return}if(e.target.id==="save")save();if(e.target.id==="close")OBR.modal.close(RESOURCE_MODAL_ID)});for(const el of [$("#pv-input"),$("#pd-input")])el.addEventListener("input",()=>setValue(el.id.startsWith("pv")?"PV":"PD",el.value));init().catch(e=>{$("#loading").textContent=e.message||"ERRO AO CARREGAR";console.error(e)});
